title: "joz_ blog"
author: "joz"
description: "experimental"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
# theme: jekyll-theme-slate

#remote_theme: niklasbuschmann/contrast@v2.11
#plugins:
#  - jekyll-remote-theme
