title: "joz_   blog"
author: "joz"
description: "Made with <b style=\"color: #f45;\"attention!!lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# theme: jekyll-theme-slate
